dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0        # For API calls to Flask
  speech_to_text: ^6.4.1 # For voice input
  flutter_tts: ^3.8.3  # For voice output (Text-to-Speech)
  flutter_vibrate: ^2.0.0 # For haptic feedback